baseURL = "https://lucent-torrone-f9024a.netlify.app"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Portio"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Prices"
url = "#resume"  #need to update with prices
weight = 4
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 5

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#faq"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Sit Doggie 2022"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "UA-26071497-1"
logo = "images/site-navigation/logo.png"

[params.address]
address = "New Market, Maryland"
email = "dogwalker@sitdoggie.com"
openingHours = "Open from 8am to 5pm (closed Saturday & Sundays)"
phone = "(240) 313-0748"

[params.map]
APIkey = "AIzaSyCge1y5zhl3MODmxUhf1URc-Rv1e6nd30w"
latitude = "39.382603"
longitude = "-77.269424"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/SitDoggie"
weight = 1
